apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kattalocalb
  name: kattalocalb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kattalocalb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kattalocalb
    spec:
      containers:
      - image: shukad33/kattalocalbackend
        name: kattalocalbackend
        resources: {}
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kattalocalb
  name: kattalocalb
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kattalocalb
  type: ClusterIP
status:
  loadBalancer: {}
