
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/katta_local
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true
  sql.init.mode: always

server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    root: DEBUG
