
spring:
  datasource:
    url: jdbc:mysql://localhost:5432/katta_local
    username: db_user
    password: 123qwe
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    root: DEBUG
